### ISSUE TITLE
client - add ssh key - with no key/argument crashes

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#24]
[atc ~]$ add ssh key

```
Roothack updates available:
  -> pip install https://files.allthingsconnect.com/roothack-0x312e322e326234.tar.gz --update
Traceback (most recent call last):
  File "/usr/local/bin/roothack", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/atc/roothack.py", line 56, in main
    run_shell()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/atc/roothack.py", line 32, in run_shell
    Shell(_app_v['setup'].api, _app_v['setup'].cli_version)
  File "/usr/local/lib/python2.7/dist-packages/atc/atc.py", line 85, in __init__
    self.loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/lib/python2.7/dist-packages/atc/command.py", line 27, in keypress
    urwid.emit_signal(self, 'done', self.get_edit_text())
  File "/usr/local/lib/python2.7/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/local/lib/python2.7/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/local/lib/python2.7/dist-packages/atc/atc.py", line 116, in execute
    self.command_wrapper(str(content))
  File "/usr/local/lib/python2.7/dist-packages/atc/atc.py", line 132, in command_wrapper
    args = {"key": "{}".format(content_args[1])}
IndexError: list index out of range

```

**Comment by geothird** [comment]
This version should resolve the issue
```shell
$ pip install http://files.roothack.org/clients/roothack-1.2.2b4.tar.gz
```
